# netlify.toml
[build]
  # Diret칩rio base onde seu projeto frontend est치
  base = "frontend/"

  # Comando que o Netlify deve rodar para construir o site
  command = "npm run build"

  # Pasta que ser치 publicada ap칩s o build
  publish = "frontend/dist"